# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0002_auto_20171127_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleccion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
