# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0004_mesa_votos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partidos',
            old_name='nuevaEleccion',
            new_name='eleccion',
        ),
    ]
