# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0005_auto_20171128_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='eleccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='votaciones.eleccion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mesa',
            name='mesa',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together=set([('eleccion', 'mesa')]),
        ),
    ]
