# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0006_auto_20171128_1354'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votos',
            unique_together=set([('mesa', 'partidos')]),
        ),
    ]
